Feat/user updates
hicsail/nist-frontend pull request #59
Opened 2023-08-17 18:02 UTC by am5815

User update actions

2023-08-17 18:49 UTC, cbolles commented on src/contexts/User.tsx
> +  setUser: () => {},
Something you may want to check out is the `SnackbarProvider` Greg has made. It would help reduce the amount of error handling that needs to take here, plus then error handling is easier everywhere else in the application

2023-08-24 14:39 UTC, gregfrasco requested changes

2023-08-24 14:39 UTC, gregfrasco commented on src/contexts/User.tsx
> +  updating: boolean;
You don't seem to be using these error messages

2023-08-24 14:39 UTC, gregfrasco commented on src/pages/Account.tsx
> +  const [snackbarMessage, setSnackbarMessage] = React.useState<string>('');
Instead of having a local stackbar we can replace it with a global one using a snack bar provider. That way you can trigger snackbar here as well as in your contexts. So we don't need to pass in success or error messages into each page.

https://github.com/hicsail/authentication-service/blob/main/packages/client/src/context/snackbar.context.tsx

2023-08-28 18:14 UTC, cbolles approved these changes

2023-08-29 17:58 UTC, gregfrasco approved these changes

2023-08-29 17:59 UTC, merged